Add “switch” checkbox
axel-springer-kugawana/iwb_serenity pull request #26
Opened 2022-04-07 23:57 UTC by meduzen-immoweb

It’s all of these:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/76440122/162337050-311ac60d-ac3b-4248-99ab-b4acc88406ca.png">

I couldn’t find any application the current `.input--switch` is used, so I completely deleted it (it’s duplicate from the new `.switch`). Let me know if it wasn’t a safe move.

The code extensively use CSS custom properties. Because our need is an immediate project, I suggest we only focus of having the right HTML and CSS, then publish an update to Serenity. And later we can 1) externalize the component 2) make the accessibility right (especially the “waiting” state). What do you think?

See HTML examples in the [forms.md](https://github.com/axel-springer-kugawana/iwb_serenity/blob/34d5774a0bf886cfd2e1bbb2621a3553db759a2f/docs/css/components/forms.md#input-switch).

Let’s discuss the open questions in the comments or on Slack.

2022-04-20 08:03 UTC, EmmaPepin commented
@meduzen-immoweb Thanks for the building site ;-) 

Indeed, there is no place in our code where we use the input--switch, so can be deleted but to be mentionned in our doc if people in the world have implemented this component.

Keep HTML as before, more accessible for label, as it : 

```
<label for="exampleSwitchMinimalSmall" class="switch switch--small">
        <input type="checkbox" name=""switchName" class="switch__input" value="value" id="exampleSwitchMinimalSmall">
        <span class="switch__checkbox">I’m a label</span>
</label>
```

Add the option to set the label before (as in doc) of after the toggle (as in figma, Pro app, classifieds list in user profile).
https://www.figma.com/file/PwYcpgzuMycHTS7NxLpvX6/*draft-Back-office-%26-masquarade?node-id=1240%3A40403

I think we can use classname "input-toggle" in place of "switch", more relevant, because "switch" is more used with button and not an input, and you talk about switch behaviour like a toggle in the doc ;-) 

https://kittygiraudel.com/2021/04/05/an-accessible-toggle/
https://www.bootstraptoggle.com/

I tested all status, it works fine 👍 Custom properties 💥😄 

Okay to externalize component and make accessibility right later.

And keep classname "switch" to create a new type of button "button--switch", only used to display/hide content, without keeping a value form, as used in the new search box in the homepage (for sale, for rent, estimate). 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role
Tab select in figma : https://www.figma.com/file/RJ3qd2oNEKEy4XcVPZQEEs/IW---Design-system?node-id=409%3A0

2022-04-21 08:59 UTC, meduzen-immoweb commented
My idea with was to only develop the checkbox part and let the user decide how to deal with the space inside the label, because we don’t have a lot of use cases, yet, and the space between the toggle and the label is not the same:

(I blurred the label as the content isn’t public.)
![Capture d’écran 2022-04-20 à 21 h 25   37](https://user-images.githubusercontent.com/76440122/164308411-96f0758c-7154-4986-bd6c-612da7ea6a48.png)
![Capture d’écran 2022-04-20 à 21 h 25   12](https://user-images.githubusercontent.com/76440122/164308417-1270ab73-85bc-425f-8143-0f90f14f3211.png)

But indeed it’s best to provide a default value (as we have for most or all components) and customization for the inner spacing, and probably allow customization through a custom property for it.

So I updated the PR with 8px as default space when you use the `switch--margin-right` or `switch--margin-left`. And where a different size is needed, two custom properties (`--switch-margin-right` and `--switch-margin-left`).

Then users wanting the text label before/after the checkbox can swap the HTML order. I also documented this.

> I think we can use classname "input-toggle" in place of "switch"

I agree, but the design team named it _switch_, so I sticked to their choice. Either we propose them to rename, either we ignore it and change anyway (but I guess the wanted practice is to follow the naming, not sure however 🤔), either we use switch. What do you think?

2022-04-21 11:12 UTC, EmmaPepin commented
About the naming, Design Team uses the term "switch", as a group of "toggle" in Figma, so we can use input--toggle :-p 
![image](https://user-images.githubusercontent.com/47316844/164446021-8a239f63-7ff7-4b4e-b10c-c8ba7c1fd4ed.png)

2022-04-25 09:47 UTC, EmmaPepin requested changes

2022-04-25 09:47 UTC, EmmaPepin commented on docs/.vuepress/components/Example/InputToggle.vue
> +                    'toggle--no-icons': !icons,
Why usage of plural on icon class ? 'toggle--no-icon' is adequate, because we can set only one SVG.

2022-04-25 10:00 UTC, meduzen-immoweb commented on docs/.vuepress/components/Example/InputToggle.vue
> +                    'toggle--no-icons': !icons,
Actually, this one disables two icons: the check and the cross.

With icons ❌ ✔ :
![image](https://user-images.githubusercontent.com/76440122/165066879-f582e399-02ed-4511-ac10-03e771f376ef.png) ![image](https://user-images.githubusercontent.com/76440122/165066916-c2e85967-a1cc-405b-9d8b-88a65871be28.png)

Without icons:
![image](https://user-images.githubusercontent.com/76440122/165066942-f924be95-472a-4d39-8810-e594c0372a6c.png) ![image](https://user-images.githubusercontent.com/76440122/165066957-c2f58b81-24ff-4d40-a2bd-c11d711af977.png)

2022-04-25 10:04 UTC, EmmaPepin commented on docs/.vuepress/components/Example/InputToggle.vue
> +                    'toggle--no-icons': !icons,
okay, but we see one at a time, this mislead me ;-) Let as it.

2022-04-25 10:06 UTC, EmmaPepin approved these changes

2022-04-25 12:40 UTC, EmmaPepin commented
@meduzen-immoweb You can remove $size-36-fixed: 2.25rem; from sizes.scss and set the right size to the existing $size-36, because when we use $size-36 in apps, we fixed by redefining it with right size ;-).
And fix bad word "convertation" to "conversion" in the header comment.

2022-04-25 13:22 UTC, meduzen-immoweb commented
> @meduzen-immoweb You can remove $size-36-fixed: 2.25rem; from sizes.scss and set the right size to the existing $size-36, because when we use $size-36 in apps, we fixed by redefining it with right size ;-). And fix bad word "convertation" to "conversion" in the header comment.

Great! Done. 🚀

2022-05-02 10:16 UTC, merged