INB-902-903: Update fonts and colors
axel-springer-kugawana/iwb_serenity pull request #68
Opened 2024-01-17 13:05 UTC by aviv-danielungureanu

2024-01-18 07:53 UTC, aviv-sergiuvulc approved these changes

2024-01-18 14:54 UTC, coroiandaniel commented on src/fonts/_gratimo-grotesk.scss
> +    src: url("../fonts/gratimo-grotesk-regular.woff2") format("woff2"),
This scss file does not make sense to be in the _fonts_ folder.
Normally, it should also be somewhere in the src/scss folder.
For this, you can create a new folder called fonts in the src/scss folder and this file will be there.
And after this change, the import in serenity.scss should also be: @import "fonts/gratimo-grotesk", thus respecting the correct structure of the files.

And the content of this url will have to be modified to match the new route.

We already have something similar in the Immoweb application.

2024-01-19 07:56 UTC, coroiandaniel requested changes

2024-01-19 07:56 UTC, coroiandaniel commented on src/scss/serenity.scss
> +@import "../fonts/gratimo-grotesk";
Importing in this way the projects that use serenity will have the error in the image if they don't add that file exactly in the same path as you.
For this, you will have to proceed as I mentioned in the previous comment. 


And for the path from the fontface url, I think will be ok if you will use a variable ($fonts-url) to contain the right path for you, and in everyone's projects to define them according to the structure of their project.
In this way we will avoid errors like this.

![err](https://github.com/axel-springer-kugawana/iwb_serenity/assets/104442982/e45a468a-1da5-4871-bc3f-88d2c7f28c86)

2024-01-19 15:06 UTC, coroiandaniel reviewed
The documentation page indicating the fonts used should also be updated (docs\css\bases\typography.md).

2024-01-19 15:14 UTC, coroiandaniel commented on package.json
>      "watch:js": "nodemon --watch src/js --ext vue --exec \"npm run js\"",
Add also `"watch:fonts": "nodemon --watch src/fonts --exec \"npm run fonts\""` as it is for images, js, css.

2024-01-22 09:41 UTC, coroiandaniel requested changes

2024-01-22 09:41 UTC, coroiandaniel commented on docs/css/bases/typography.md
>  These two fonts are not loaded by Serenity. You can include them either by using Google Fonts CDN either by (preferably) self-hosting the fonts and writing your own `@font-face` declarations.
Now we no longer have 2 fonts (only one - regular and bold), and it can no longer be loaded via CDN, so this text will also have to be updated into something like:
```
This font is not loaded by Serenity. You can include it by self-hosting the fonts and writing your own `@font-face` declarations.
You cand find the fonts in `src/fonts` folder.
```

2024-01-22 09:41 UTC, coroiandaniel commented on docs/css/bases/typography.md
>  Using Google Fonts, link these stylesheets in the `<head>` tag of your page.
This text should be removed.

2024-01-22 09:41 UTC, coroiandaniel commented on docs/css/bases/typography.md
>  If these fonts are not available, they will fall back on other fonts, depending on which ones are available on your system. The font stacks are:
Change to (singular): `If this font is not available, it will fall back on other fonts, depending...`

2024-01-22 11:43 UTC, coroiandaniel approved these changes

2024-01-29 14:35 UTC, merged